setting_xpm=[
"16 16 30 1",
" 	c None",
".	c #999999",
"+	c #A3A3A3",
"@	c #FFFFFF",
"#	c #FAFAFA",
"$	c #F1F1F1",
"%	c #EBEBEB",
"&	c #909090",
"*	c #E2E2E2",
"=	c #D77037",
"-	c #FFE7C7",
";	c #FFBE8F",
">	c #FAB990",
",	c #F7F7F7",
"'	c #D7D7D7",
")	c #FFDDB6",
"!	c #FFB07A",
"~	c #F2A474",
"{	c #CFCFCF",
"]	c #C7C7C7",
"^	c #E5E5E5",
"/	c #BFBFBF",
"(	c #DEDEDE",
"_	c #B7B7B7",
":	c #FFEDD0",
"<	c #FFCBA3",
"[	c #FCC29E",
"}	c #FBFBFB",
"|	c #DADADA",
"1	c #C2632F",
" ...  ++++ ++++ ",
" .@.  +@@+ +@@+ ",
" .@.  +@@+ +@@+ ",
" .@.  +@@+++@@+ ",
" .@.  +@#@@@#@+ ",
" .@.  +@@$%$@@+ ",
"..@.. &++#*#++& ",
"=-;>=   +,',+   ",
"=)!~=   +${$+   ",
"=)!~=   +%]%+   ",
"=)!~=   +^/^+   ",
"=)!~=   +(_(+   ",
"=:<[=   +}|}+   ",
"1===1   &+++&   ",
"                ",
"                "]
plugin_xpm=[
"16 16 33 1",
" 	c None",
".	c #277AA9",
"+	c #2386B8",
"@	c #1C8DC4",
"#	c #2E8CBE",
"$	c #2E96CE",
"%	c #3A9ED6",
"&	c #34A6DE",
"*	c #47A7E0",
"=	c #52B2E6",
"-	c #55B3EF",
";	c #5FBBF7",
">	c #5AC2FB",
",	c #69BFED",
"'	c #6CC2F7",
")	c #60C7FF",
"!	c #72C5F4",
"~	c #79C6EF",
"{	c #6DCAFE",
"]	c #86C9F3",
"^	c #71D1FE",
"/	c #7CD0FF",
"(	c #86CEF8",
"_	c #7DD7FF",
":	c #9AD6FC",
"<	c #8BDCFE",
"[	c #95DCFF",
"}	c #91E3FD",
"|	c #9FDFFE",
"1	c #9EEBFF",
"2	c #B6ECFF",
"3	c #A9F0FF",
"4	c #B9F6FE",
"     %%%        ",
"    &24!        ",
"    !43[$       ",
" %===11*%%*     ",
" %411}}1332%    ",
" %2______<[$    ",
" %2(<^^^^^/%,&  ",
" +$.,/))){//[|% ",
" $~&!{;;;>{{{|% ",
" %|/{'>;;;!=:~# ",
" %(-;!,'--!+@.  ",
" $]-'%+!-;($    ",
" #~]:*%:]~~#    ",
"  .#%# @@+.     ",
"                ",
"                "]
about_xpm=[
"16 16 33 1",
" 	c None",
".	c #3198D0",
"+	c #349AD2",
"@	c #7CC3EC",
"#	c #9EE1FF",
"$	c #B0EFFF",
"%	c #4CA2D6",
"&	c #A4E8FF",
"*	c #7DD1FF",
"=	c #39A7E6",
"-	c #90DDFF",
";	c #FEFFFC",
">	c #71BDE5",
",	c #81D4FC",
"'	c #2792CA",
")	c #98D4F9",
"!	c #70CCFF",
"~	c #5BC3FC",
"{	c #68C6FA",
"]	c #94D6FF",
"^	c #57BFF9",
"/	c #89CCF6",
"(	c #66B9EE",
"_	c #5CB7F2",
":	c #167AA9",
"<	c #77C1F1",
"[	c #55B2EC",
"}	c #4DACE6",
"|	c #489FD2",
"1	c #1F6D99",
"2	c #60B6E4",
"3	c #1B6188",
"4	c #1B82B3",
"      ....      ",
"    +@#$$#@+    ",
"   %#&*==*&#%   ",
"  +#--#;;#--#+  ",
"  >#,,&;;&,,#>  ",
" ')*!!~==~!!*)' ",
" .-!{{];;]{{!-. ",
" .]{^^);;)^^{]. ",
" '/(__/;;/__(/' ",
" :><[[/;;/[[<>: ",
"  ./(}/;;/}(/.  ",
"  :|@(}==}(@|:  ",
"   1.2@<<@2.1   ",
"     34..43     ",
"                ",
"                "]
accept_xpm=[

"16 16 136 2",
"   c #1D6C1A",
".  c #1E6E1A",
"X  c #1E701A",
"o  c #1E711A",
"O  c #1F711B",
"+  c #1E731A",
"@  c #1F781B",
"#  c #1E7A1B",
"$  c #1F7A1B",
"%  c #1E7F1B",
"&  c #1F831B",
"*  c #208A1B",
"=  c #20881C",
"-  c #2D961C",
";  c #2F961C",
":  c #329D1D",
">  c #42A91F",
",  c #42AB1F",
"<  c #42AD1F",
"1  c #4C973D",
"2  c #4BB426",
"3  c #52B92B",
"4  c #52BB2D",
"5  c #54BB2D",
"6  c #54BD31",
"7  c #55BE34",
"8  c #55C034",
"9  c #59C236",
"0  c #5BC239",
"q  c #4E9B41",
"w  c #52A042",
"e  c #5EA948",
"r  c #64B04C",
"t  c #6CB656",
"y  c #6DB757",
"u  c #6AB950",
"i  c #6EB558",
"p  c #6FB558",
"a  c #6FB559",
"s  c #70BF57",
"d  c #74B75B",
"f  c #74B75C",
"g  c #70B859",
"h  c #71B95B",
"j  c #72B95B",
"k  c #73BA5C",
"l  c #71BE5F",
"z  c #7DB766",
"x  c #77BC60",
"c  c #7CBA64",
"v  c #7DBC66",
"b  c #7DBE67",
"n  c #7FB869",
"m  c #74C259",
"M  c #6FC261",
"N  c #6FC361",
"B  c #6EC461",
"V  c #6EC462",
"C  c #6EC563",
"Z  c #6FC664",
"A  c #70C163",
"S  c #71C463",
"D  c #74C364",
"F  c #70C765",
"G  c #73C766",
"H  c #79C164",
"J  c #7EC169",
"K  c #7EC76F",
"L  c #72C868",
"P  c #74C868",
"I  c #75C868",
"U  c #76C969",
"Y  c #76CA6A",
"T  c #79C96B",
"R  c #7ACC6D",
"E  c #7FCA70",
"W  c #83BE6D",
"Q  c #87C272",
"!  c #85C575",
"~  c #89C476",
"^  c #80CA73",
"/  c #80CC72",
"(  c #83CE77",
")  c #87C979",
"_  c #8BC878",
"`  c #90CE7F",
"'  c #96C783",
"]  c #9AC787",
"[  c #96CB86",
"{  c #97CC85",
"}  c #98CB86",
"|  c #9ACA87",
" . c #98CC87",
".. c #96CD88",
"X. c #99CD8A",
"o. c #9DCE8B",
"O. c #99D18B",
"+. c #99D08C",
"@. c #9AD48D",
"#. c #9FD291",
"$. c #9BD791",
"%. c #9DD892",
"&. c #A1D695",
"*. c #A1D795",
"=. c #A3D796",
"-. c #ABD29B",
";. c #ABD39B",
":. c #AFD7A0",
">. c #AED7A1",
",. c #AEDCA5",
"<. c #AFDCA6",
"1. c #B3D9A5",
"2. c #B4D9A5",
"3. c #B4DAA6",
"4. c #B1DDA7",
"5. c #B2DBA8",
"6. c #B5DBA8",
"7. c #B4DDAA",
"8. c #B4DFAC",
"9. c #B5DFAC",
"0. c #B5E1AE",
"q. c #B7E1AF",
"w. c #B7E1B0",
"e. c #BEE3B6",
"r. c #BFE3B8",
"t. c #C0E4B9",
"y. c #D6EED2",
"u. c #D9ECD4",
"i. c #E6F4E3",
"p. c #EDF7EB",
"a. c #F1F9F0",
"s. c #F4FAF2",
"d. c #FCFDFB",
"f. c #FDFEFD",
"g. c gray100",
"h. c None",

"h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.",
"h.h.h.h.h.h.0 6 4 3 h.h.h.h.h.h.",
"h.h.h.h.9 m =.,.,.&.u , h.h.h.h.",
"h.h.h.8 ` q.%.( ( %.0._ : h.h.h.",
"h.h.7 ` 0.R Y L P I T 8.~ - h.h.",
"h.h.s q.R L F C V S e.K 9.e h.h.",
"h.5 *.$.U Z B N M t.g.i.O.o.= h.",
"h.2 4./ G w.y.A r.g.d.+.J >.% h.",
"h.< <.E ^ a.g.p.g.d...h b :.# h.",
"h.> #.@.D ) s.g.f.[ y j { ] @ h.",
"h.h.r 7.H l ! u.X.t i f 3.q h.h.",
"h.h.; Q 5.x k g a p d 1.n o h.h.",
"h.h.h.* W 6. .v c } 2.z   h.h.h.",
"h.h.h.h.& w | ;.-.' 1 . h.h.h.h.",
"h.h.h.h.h.h.$ + X O h.h.h.h.h.h.",
"h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h."
]
cancel_xpm=[

"16 16 104 2",
"   c #ED0000",
".  c #EF0000",
"X  c #F10000",
"o  c #F30000",
"O  c #F50000",
"+  c #F70000",
"@  c #F90000",
"#  c #FB0000",
"$  c #FD0000",
"%  c red",
"&  c #F50909",
"*  c #F50B0B",
"=  c #F50C0C",
"-  c #F60F0F",
";  c #F61010",
":  c #F71212",
">  c #F71313",
",  c #F81616",
"<  c #F81717",
"1  c #F11B14",
"2  c #F21B14",
"3  c #F51B16",
"4  c #F61D18",
"5  c #F5201A",
"6  c #F9231D",
"7  c #FA251F",
"8  c #FC2722",
"9  c #F92924",
"0  c #FF2B26",
"q  c #FC2828",
"w  c #FC2929",
"e  c #FA2F2A",
"r  c #FD2C2C",
"t  c #FD2D2D",
"y  c #FD2F2F",
"u  c #F73333",
"i  c #F73530",
"p  c #F73434",
"a  c #FD3030",
"s  c #FE3232",
"d  c #FE3333",
"f  c #FB3732",
"g  c #FE3434",
"h  c #F83939",
"j  c #F93A3A",
"k  c #F93B3B",
"l  c #FC3C38",
"z  c #F93D3D",
"x  c #FA3E3E",
"c  c #F74232",
"v  c #F74333",
"b  c #F74334",
"n  c #F74434",
"m  c #F84535",
"M  c #F84738",
"N  c #F84838",
"B  c #F8493A",
"V  c #F84B3C",
"C  c #F94C3C",
"Z  c #F94E3F",
"A  c #FB4742",
"S  c #FE4743",
"D  c #FF4743",
"F  c #FC4747",
"G  c #FC4848",
"H  c #FC4A4A",
"J  c #FC4B4B",
"K  c #FB4C48",
"L  c #FC4C4C",
"P  c #FA5142",
"I  c #FA5344",
"U  c #FB5749",
"Y  c #FB584A",
"T  c #FC5D4F",
"R  c #FD5D4F",
"E  c #FD5050",
"W  c #FE5252",
"Q  c #FD5F52",
"!  c #FF5B58",
"~  c #FE6154",
"^  c #FE6255",
"/  c #FE6356",
"(  c #FE6457",
")  c #FE6558",
"_  c #FE675A",
"`  c #FF685B",
"'  c #FF695C",
"]  c #FF6A5D",
"[  c #FDC5C5",
"{  c #FDC9C9",
"}  c #FECACA",
"|  c #FECBCB",
" . c #FECCCC",
".. c #FFCFCF",
"X. c #FEEAEA",
"o. c #FEEBEB",
"O. c #FEECEC",
"+. c #FFECEC",
"@. c #FFEDED",
"#. c #FEF1F1",
"$. c #FFF1F1",
"%. c #FFF2F2",
"&. c #FFF3F3",
"*. c None",

"*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.",
"*.*.*.*.% % % % $ $ $ $ *.*.*.*.",
"*.*.*.% 0 ' ` _ ) / ~ 8 # *.*.*.",
"*.*.% 0 ] D g s a t l T 7 + *.*.",
"*.% 0 ] ! ..W y r J  .K U 6 O *.",
"*.% ` S ..&.@.L H +.%.} e P o *.",
"*.% _ d E @.&.@.@.%.O.x < Z X *.",
"*.$ ( a t J @.%.%.+.z , > V X *.",
"*.$ ^ r w G @.%.%.O.j : - N X *.",
"*.$ Q q F +.%.+.O.$.X.p * m . *.",
"*.# R f | %.o.k h X.#.[ 4 v . *.",
"*.@ 7 Y A { k > ; u [ i n 2   *.",
"*.*.+ 6 I 9 : - = & 3 v 1   *.*.",
"*.*.*.O 5 C B M m b c 1   *.*.*.",
"*.*.*.*.X X X X . .     *.*.*.*.",
"*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*."
]
cog_xpm=[

"16 16 80 1",
"  c #494949",
". c #4E4E4E",
"X c #515151",
"o c #535353",
"O c #585858",
"+ c #5B5B5B",
"@ c gray38",
"# c #626262",
"$ c #646464",
"% c DimGray",
"& c gray42",
"* c #6D6D6D",
"= c gray43",
"- c #6F6F6F",
"; c #797979",
": c #808080",
"> c #818181",
", c gray51",
"< c #838383",
"1 c gray52",
"2 c gray53",
"3 c #898989",
"4 c gray55",
"5 c gray56",
"6 c gray61",
"7 c gray62",
"8 c #A0A0A0",
"9 c gray63",
"0 c gray64",
"q c #A5A5A5",
"w c gray65",
"e c #A7A7A7",
"r c gray66",
"t c #AAAAAA",
"y c #ACACAC",
"u c gray69",
"i c #B1B1B1",
"p c #B2B2B2",
"a c gray71",
"s c #B7B7B7",
"d c #B9B9B9",
"f c gray73",
"g c #BCBCBC",
"h c gray74",
"j c gray",
"k c gray75",
"l c #C0C0C0",
"z c #C1C1C1",
"x c gray76",
"c c #C3C3C3",
"v c gray77",
"b c #C5C5C5",
"n c #C6C6C6",
"m c gray78",
"M c #C8C8C8",
"N c gray79",
"B c #CACACA",
"V c #CBCBCB",
"C c gray80",
"Z c #CDCDCD",
"A c #CECECE",
"S c gray81",
"D c gray82",
"F c #D2D2D2",
"G c gray83",
"H c #D5D5D5",
"J c gray84",
"K c #D8D8D8",
"L c gray85",
"P c gray86",
"I c gainsboro",
"U c #DDDDDD",
"Y c gray87",
"T c #E2E2E2",
"R c #E4E4E4",
"E c gray90",
"W c #E7E7E7",
"Q c #E9E9E9",
"! c gray93",
"~ c None",

"~~~~~~~mv~~~~~~~",
"~~~~~~mERy~~~~~~",
"~~DAB~xYUp~ye0~~",
"~~I!PxjJGuyVWs~~",
"~~vIGLPJGLFVM;~~",
"~~bGCNf69xnzs3~~",
"MvlKZg,~~5cxZ42<",
"vQJNAq~~~~yvfnU&",
"kTFnZi~~~~rxslF@",
"058SnC7~~5zgd$Oo",
"~~ybzbmtezjat%~~",
"~~wHbVDNmCbhV=~~",
"~~gYw<1vx*=wF:~~",
"~~>-$~<Vm#~O. ~~",
"~~~~~~>hp+~~~~~~",
"~~~~~~~OX~~~~~~~"
]
header_xpm=[
"256 57 256 2",
"  	c #A53905",
". 	c #9D3D08",
"+ 	c #963F11",
"@ 	c #904116",
"# 	c #864420",
"$ 	c #89441B",
"% 	c #804625",
"& 	c #7C4827",
"* 	c #76492F",
"= 	c #834720",
"- 	c #734B2F",
"; 	c #8B654B",
"> 	c #A3633B",
", 	c #766D61",
"' 	c #816D55",
") 	c #737165",
"! 	c #6D7571",
"~ 	c #71786C",
"{ 	c #7D7664",
"] 	c #5E7E7E",
"^ 	c #6B7C76",
"/ 	c #7E7B6D",
"( 	c #97775D",
"_ 	c #957955",
": 	c #8A7D64",
"< 	c #E36B29",
"[ 	c #838074",
"} 	c #7A8376",
"| 	c #BC763B",
"1 	c #D87035",
"2 	c #E06F31",
"3 	c #C6763B",
"4 	c #EC6D2F",
"5 	c #AE7D4A",
"6 	c #57909B",
"7 	c #8A8673",
"8 	c #5E9095",
"9 	c #E9712F",
"0 	c #7B8D86",
"a 	c #B0845C",
"b 	c #EA7732",
"c 	c #898D7F",
"d 	c #ED7A3C",
"e 	c #AC8969",
"f 	c #EC7A42",
"g 	c #9C8D74",
"h 	c #5B9DAC",
"i 	c #8C9486",
"j 	c #DB8445",
"k 	c #639EA9",
"l 	c #C38B5C",
"m 	c #E8834A",
"n 	c #ED8246",
"o 	c #A19482",
"p 	c #879C9C",
"q 	c #869E96",
"r 	c #E88854",
"s 	c #F18650",
"t 	c #949B97",
"u 	c #AB9876",
"v 	c #80A19D",
"w 	c #BF946B",
"x 	c #A4998D",
"y 	c #9C9D88",
"z 	c #DA8F60",
"A 	c #92A091",
"B 	c #9A9E90",
"C 	c #B99972",
"D 	c #F28C53",
"E 	c #7CA7AA",
"F 	c #AE9D83",
"G 	c #60AFC4",
"H 	c #E5925D",
"I 	c #29BBF1",
"J 	c #EF905B",
"K 	c #A7A187",
"L 	c #B59E85",
"M 	c #67B0BF",
"N 	c #6FAEBE",
"O 	c #74AEB8",
"P 	c #7CACB8",
"Q 	c #A5A48F",
"R 	c #97A79B",
"S 	c #9DA695",
"T 	c #3ABBEB",
"U 	c #2DBEF4",
"V 	c #F8925F",
"W 	c #44BAE5",
"X 	c #57B6D6",
"Y 	c #F3945E",
"Z 	c #8AABB0",
"` 	c #4FB8DD",
" .	c #5EB5CF",
"..	c #94AAA3",
"+.	c #71B4BD",
"@.	c #AAA798",
"#.	c #D59F70",
"$.	c #30C3F2",
"%.	c #81B1B7",
"&.	c #98ABAF",
"*.	c #67B7CB",
"=.	c #40BFEF",
"-.	c #85B1B2",
";.	c #7AB4BF",
">.	c #8EB0AC",
",.	c #6FB7C6",
"'.	c #C3A585",
").	c #44C1F2",
"!.	c #F69B69",
"~.	c #F19C6F",
"{.	c #57BEE4",
"].	c #4FC0EB",
"^.	c #A0B0A2",
"/.	c #AEAD98",
"(.	c #4DC2E6",
"_.	c #37C7F6",
":.	c #AAAE9E",
"<.	c #44C5EE",
"[.	c #CAA981",
"}.	c #48C4F5",
"|.	c #61BFDF",
"1.	c #58C3E1",
"2.	c #67C0DA",
"3.	c #B9AF95",
"4.	c #6EBFD4",
"5.	c #76BECD",
"6.	c #49C9F2",
"7.	c #80BEC9",
"8.	c #F3A47B",
"9.	c #57C7F2",
"0.	c #A1B8B0",
"a.	c #8FBCBF",
"b.	c #FAA477",
"c.	c #99BBB7",
"d.	c #ABB8A9",
"e.	c #4ECCF6",
"f.	c #59CAEF",
"g.	c #6DC6E0",
"h.	c #62C9E8",
"i.	c #C2B4A4",
"j.	c #B4B8A9",
"k.	c #77C6DB",
"l.	c #B7BAA4",
"m.	c #BEB8A4",
"n.	c #7FC6D6",
"o.	c #FAAB81",
"p.	c #F5AC86",
"q.	c #87C7D1",
"r.	c #A1C3BF",
"s.	c #C5BCA2",
"t.	c #B1C1B3",
"u.	c #9AC7CA",
"v.	c #ABC5BC",
"w.	c #D5BC9A",
"x.	c #EDB690",
"y.	c #67D4F5",
"z.	c #E0BB8F",
"A.	c #FCB38C",
"B.	c #F6B591",
"C.	c #FFB589",
"D.	c #8DD0DA",
"E.	c #89D1E1",
"F.	c #84D2E7",
"G.	c #95CFDA",
"H.	c #A4CDD0",
"I.	c #9AD0D4",
"J.	c #BCC9BB",
"K.	c #CAC5BA",
"L.	c #78D8F1",
"M.	c #ACCDC9",
"N.	c #72DAF9",
"O.	c #B6CBCA",
"P.	c #82D7F1",
"Q.	c #B6CDBE",
"R.	c #D1C7AD",
"S.	c #FEBC98",
"T.	c #80D9ED",
"U.	c #88D7EC",
"V.	c #74DCFB",
"W.	c #7ADBF4",
"X.	c #AECFD2",
"Y.	c #D0C8B4",
"Z.	c #8DD7E6",
"`.	c #C6CBBD",
" +	c #93D7E0",
".+	c #76DDFC",
"++	c #9BD5E0",
"@+	c #B6D0C8",
"#+	c #CBCCB6",
"$+	c #BECFC8",
"%+	c #7EDEF7",
"&+	c #A0D7DD",
"*+	c #FDC29D",
"=+	c #A5D7D6",
"-+	c #ADD5D7",
";+	c #B0D5D1",
">+	c #85DFF2",
",+	c #80E0FA",
"'+	c #A1DBE6",
")+	c #9ADDE7",
"!+	c #95DEEE",
"~+	c #83E3FC",
"{+	c #92E0F6",
"]+	c #8DE2FD",
"^+	c #8AE4F7",
"/+	c #DED2B7",
"(+	c #C7D9D2",
"_+	c #ACE1E6",
":+	c #B5E0E1",
"<+	c #C3E0DD",
"[+	c #D3DDCE",
"}+	c #C6E0D7",
"|+	c #DFDBC5",
"1+	c #ACE7F2",
"2+	c #BFE4E0",
"3+	c #A1EBFA",
"4+	c #AAE9FA",
"5+	c #B3E9EE",
"6+	c #AFEAF6",
"7+	c #BEE7E9",
"8+	c #BBE8EF",
"9+	c #ADEDFE",
"0+	c #ABEFF9",
"a+	c #CBE8E5",
"b+	c #C8E9EC",
"c+	c #B3EEF9",
"d+	c #B7EDFF",
"e+	c #DDE6D8",
"f+	c #B4EFFA",
"g+	c #BCEEFB",
"h+	c #C4EDEF",
"i+	c #B6F1FC",
"j+	c #C0EFF6",
"k+	c #D9EBE4",
"l+	c #F4E5D2",
"m+	c #CDEEF1",
"n+	c #BFF1FE",
"o+	c #B9F4FF",
"p+	c #C0F2FF",
"q+	c #D2EFEC",
"r+	c #DAEDED",
"s+	c #E2ECE6",
"t+	c #C5F3FA",
"u+	c #C6F4FB",
"v+	c #C3F5FF",
"w+	c #C7F5FC",
"x+	c #CFF4FD",
"y+	c #C9F6FD",
"z+	c #CAF7FF",
"A+	c #D1F6FF",
"B+	c #CFF8FA",
"C+	c #CBF9FF",
"D+	c #D3F8FF",
"E+	c #CDFAFF",
"F+	c #D4F9FF",
"G+	c #D7F9FC",
"G+G+G+G+G+G+D+D+G+G+D+D+D+D+D+D+D+A+A+A+D+D+D+D+D+D+D+A+D+A+A+A+C+C+A+C+A+A+A+A+C+A+C+C+A+A+z+z+y+y+y+y+y+w+y+y+w+w+y+y+y+y+w+w+w+w+w+y+u+u+p+p+u+u+w+u+u+u+u+u+t+t+u+u+w+u+u+u+u+u+t+t+t+t+t+t+t+t+t+t+t+t+t+t+p+p+p+p+p+p+n+p+p+p+p+p+p+n+p+n+n+n+n+n+n+n+n+n+n+n+i+i+i+i+n+g+i+i+f+f+i+i+g+g+i+i+f+f+f+f+f+f+f+f+f+f+f+f+c+f+f+f+f+c+f+c+f+f+f+c+9+9+c+c+c+c+c+c+c+c+c+c+c+c+c+c+9+9+c+c+c+0+9+3+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+4+1+b+[+w.F H.)+-+%.1.6.6.e.6.f.g.a.a a <+3+3+3+4+4+3+3+3+3+3+3+3+3+4+4+3+3+3+3+3+7+/+C ",
"G+G+G+G+G+G+D+D+G+G+D+D+D+D+D+D+D+D+A+A+D+D+D+D+D+A+A+D+A+A+A+A+C+C+A+A+A+C+A+A+A+A+C+z+A+A+y+w+y+z+w+z+w+w+w+w+y+w+w+w+y+y+w+w+w+w+y+w+w+u+p+p+u+u+w+w+w+u+u+u+t+t+u+u+u+u+u+t+t+t+t+t+t+t+t+t+t+t+t+t+t+t+t+t+p+p+p+n+p+p+p+p+p+p+p+p+p+n+n+n+n+n+n+n+n+p+n+n+n+n+i+i+i+i+n+g+i+i+i+i+i+i+i+i+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+f+f+f+f+c+f+f+c+c+c+c+f+c+c+c+c+c+c+c+c+c+9+9+c+c+c+c+9+3+9+9+9+9+9+9+9+9+9+9+9+9+4+3+9+9+9+1+8+7+}+:.Q J._+)+I.;.1.6.6.6.e.h.5.q _ '.7+3+3+3+4+4+3+3+3+3+3+3+3+3+4+4+3+3+3+3+_+<+/.F ",
"G+G+G+G+G+G+D+D+D+D+D+D+D+D+D+D+D+A+A+A+D+D+A+D+A+D+A+A+D+A+A+A+C+C+A+A+z+C+A+A+z+z+A+A+y+y+A+A+y+y+w+y+y+y+y+y+u+w+w+w+w+w+w+w+y+t+w+w+u+u+u+u+w+w+w+u+u+u+u+u+u+u+u+u+u+u+u+t+u+t+t+t+t+t+t+t+t+t+t+t+t+p+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+n+n+n+n+n+n+n+n+n+i+i+n+n+i+i+g+g+i+i+i+i+i+i+i+i+i+i+i+i+f+f+g+g+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+f+f+f+c+f+c+c+f+9+f+f+f+c+c+c+c+c+9+9+c+c+9+9+0+0+c+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+3+3+3+3+4+5+[+#+y d.-+'+!+!+;.5.1.6.6.e.f.k.t ( L `.5+3+4+4+3+3+3+3+3+3+3+3+3+3+4+4+3+3+4+5+[+:...r.",
"G+G+G+G+G+G+D+D+D+D+D+D+D+D+D+D+D+D+D+A+A+D+D+D+A+D+A+A+D+A+A+A+C+y+A+A+z+C+C+A+z+z+A+A+z+y+x+x+y+y+y+y+y+w+y+y+w+y+w+w+w+w+w+w+w+w+u+w+u+w+u+t+w+w+w+w+w+u+u+u+u+t+u+t+t+u+u+u+u+t+t+t+t+t+t+t+t+t+t+t+t+p+t+t+p+p+p+p+p+p+n+p+n+p+p+p+p+p+n+n+n+n+n+n+n+n+i+i+n+n+i+i+n+n+i+i+i+i+g+g+i+i+i+i+i+f+f+f+g+g+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+c+d+d+f+f+f+c+c+9+c+c+f+c+c+c+c+c+9+9+c+c+9+9+0+0+c+9+9+9+9+9+9+9+9+9+9+9+9+9+4+9+3+0+6+5+7+}+d.y J.;+!+{+!+E.,.4.f.6.e.h.g.a.: L :.2+1+3+4+4+3+3+3+3+3+3+3+3+3+3+4+4+3+3+8+<+:.S u.G.",
"G+G+G+G+G+G+G+D+D+B+D+D+D+D+D+D+D+A+D+D+D+D+A+D+D+A+A+A+A+A+A+A+C+C+C+C+C+C+A+A+A+A+A+A+z+z+z+y+y+y+y+y+x+x+w+y+y+z+y+w+w+w+w+w+y+u+w+w+p+p+u+u+w+w+w+w+u+u+u+u+u+u+t+u+u+t+u+u+t+t+p+p+t+t+p+n+t+t+t+t+t+t+p+n+p+p+p+p+p+p+p+p+p+n+n+p+n+p+p+n+n+n+n+n+n+n+n+n+i+i+n+n+i+i+g+g+i+i+i+i+f+i+i+f+i+i+f+f+f+f+f+f+f+f+f+f+i+f+f+f+f+f+f+f+f+i+c+f+c+c+f+c+c+c+c+f+c+0+c+c+9+9+c+c+c+c+9+9+9+c+c+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+3+6+5+<+#+K ^.;+&+!+{+{+'+;.2.f.6.e.e.g.c./ 7 `.r.7+1+3+3+3+3+3+3+3+3+3+3+3+3+3+3+3+3+5+[+:.R u.E.L.",
"G+G+G+G+G+G+G+G+D+B+D+D+D+D+D+D+D+A+D+D+D+D+A+D+D+D+A+A+A+D+A+A+C+C+z+C+z+C+A+A+A+A+A+A+z+y+y+y+y+w+y+y+x+x+y+y+y+w+y+w+w+w+w+w+w+w+w+w+w+p+w+u+w+w+w+u+u+u+u+u+u+u+u+u+u+u+t+t+t+u+p+p+t+t+p+p+t+t+p+p+t+t+p+n+p+p+p+p+p+p+p+p+p+p+n+p+p+n+n+n+n+n+p+n+n+n+n+n+i+i+n+i+i+i+g+n+i+i+i+i+i+i+f+f+f+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+c+c+c+c+c+c+c+c+c+c+0+c+c+9+9+c+c+c+c+9+9+9+9+c+9+9+9+9+9+9+9+9+9+9+9+9+4+9+c+5+7+<+t.y l.;+'+{+]+{+!+I.+.1.e.e.f.g.7.} : J.c.:+1+1+3+3+3+3+3+3+3+3+3+3+3+3+3+3+1+_+2+:.S u.E.L.N.",
"G+G+G+G+G+G+D+G+D+D+G+G+D+D+D+D+D+B+D+D+D+D+D+D+D+D+C+C+A+A+A+A+C+C+A+A+C+C+A+A+A+A+A+A+y+y+y+z+y+y+y+w+w+u+w+w+y+y+w+w+w+w+w+w+w+w+u+w+y+y+w+w+w+w+u+u+u+u+u+u+u+u+u+u+u+u+t+t+t+u+t+t+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+n+p+p+n+p+n+n+n+n+n+n+n+n+n+n+o+i+i+i+i+i+i+i+i+i+f+i+i+i+i+f+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+f+f+f+f+f+f+c+f+c+c+c+c+c+c+c+f+c+c+c+c+c+c+c+c+c+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+5+}+#+Q S M._+)+!+{+{+!+!++.4.h.e.e.g.a.0 } t.@+c.5+4+3+3+3+4+3+3+3+3+4+4+3+3+3+3+3+5+[+/...u.E.L.L.N.",
"G+G+G+G+G+G+D+G+D+D+G+G+D+D+D+A+B+B+D+D+A+D+D+D+A+D+C+C+A+A+A+A+z+C+A+A+C+C+A+A+A+A+A+A+z+z+z+y+y+y+y+y+w+y+w+w+w+w+w+w+w+w+w+w+u+u+w+w+w+w+u+w+w+w+u+u+u+u+u+u+u+u+u+u+u+u+u+t+t+t+t+t+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+p+n+p+p+n+n+p+p+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+f+i+i+i+f+f+f+f+f+f+f+f+i+f+f+c+f+f+f+f+i+f+f+f+c+f+c+f+c+c+c+c+c+c+f+c+c+c+c+c+c+c+c+c+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+c+6+5+7+}+d.y l.@+'+{+^+^+]+{+)+7.4.g.f.f.h.5.q / c.X.r.-+1+4+3+3+3+4+3+3+3+3+4+4+3+3+3+1+_+<+/.S H.E.L.N.N.N.",
"G+G+G+G+G+G+G+G+D+D+D+D+D+D+D+D+A+A+D+D+D+D+D+D+A+D+A+D+A+A+C+C+A+A+A+A+A+A+A+x+C+z+A+A+y+y+A+A+y+y+y+y+y+w+w+w+y+z+y+w+y+y+w+u+w+u+w+u+u+u+w+w+u+w+u+u+u+u+u+u+t+w+t+t+t+u+u+t+p+p+t+t+t+t+t+t+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+n+p+p+p+n+p+n+n+p+n+n+n+i+i+i+i+i+i+i+i+i+i+i+i+i+g+g+f+f+i+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+f+f+f+f+f+c+f+f+f+f+f+c+9+9+c+c+c+c+c+c+c+c+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+6+8+}+Y.K ^.M._+)+{+^+^+]+]+{+&++.g.f.f.h.7.Z ~ ^.&+++>.7+1+3+3+3+3+3+3+3+3+3+3+3+3+3+4+7+`.Q ..I.F.L.N.N.N.W.",
"G+G+G+G+G+G+G+G+D+G+D+D+D+D+D+A+A+A+D+A+D+D+D+A+A+D+A+D+A+A+C+C+C+A+A+A+A+A+A+A+z+z+A+A+y+z+A+x+z+y+y+y+w+w+w+z+y+z+w+w+w+u+w+w+y+w+u+u+w+w+w+h+q+r+r+r+r+r+r+r+r+r+r+k+k+k+k+r+r+m+x+t+t+t+t+t+t+t+t+t+t+t+p+n+p+p+p+p+p+p+p+p+p+n+p+n+n+n+n+p+n+n+n+n+o+i+i+i+i+i+i+i+i+i+i+i+i+i+g+g+f+i+i+f+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+f+f+f+c+f+c+f+f+f+c+c+c+9+9+c+c+c+f+c+c+c+c+9+9+9+9+9+9+9+9+9+9+9+9+9+c+8+7+}+d.y l.;+'+{+^+^+^+]+{+{+!++.5.h.6.h.k.Z ~ ..M.&+G.H.7+1+3+3+3+3+3+3+3+3+3+3+3+4+1+7+@+y :.I.F.L.N.N.V.N.W.",
"G+G+G+G+G+G+D+D+D+D+A+D+D+D+D+A+D+D+A+A+D+D+D+D+A+D+A+A+C+C+A+A+C+C+A+A+C+C+A+A+A+A+z+z+x+x+w+y+y+y+w+y+y+y+w+y+y+w+w+w+w+w+w+w+y+u+w+p+w+w+u+q+l+- - - - - - - - - - - - - - - - l+m+p+t+t+t+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+n+p+n+p+p+p+n+p+n+n+i+i+n+n+n+n+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+f+i+i+i+f+f+f+f+f+f+f+f+c+f+f+f+f+f+f+f+i+f+f+c+c+c+f+f+c+c+c+c+c+c+c+c+c+c+0+0+9+9+c+c+c+c+0+0+9+9+9+9+9+9+9+9+c+7+[+Y.y ^.-+'+!+!+{+^+]+]+]+{+'+q.*.g.f.h.k.-.~ R &+ +-+-.5+1+4+4+3+3+3+3+3+3+3+3+3+4+5+<+#+y c.D.U.L.N.N.N.N.N.N.",
"G+G+G+G+G+G+D+D+D+D+D+D+D+A+A+D+D+D+A+A+D+A+D+D+A+A+A+A+C+C+D+A+z+z+A+A+z+z+A+A+A+A+y+y+x+y+y+y+y+y+w+y+w+y+w+y+w+y+w+w+w+w+w+w+w+u+u+u+w+w+u+r+- # *+*+*+*+*+*+*+*+*+*+*+*+*+*+# - r+p+t+t+t+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+n+p+p+p+n+n+n+n+n+p+i+i+n+p+n+n+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+f+f+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+c+c+f+f+c+c+c+c+c+c+f+c+c+c+0+9+9+9+c+c+c+c+0+0+9+9+9+9+4+c+5+8+b+(+/.Q J.;+!+^+^+^+^+^+]+{+{+!++++.g.h.h.4.%.^ B M.Z.Z.H.r.1+4+4+4+3+3+3+3+3+3+3+3+1+_+2+t.y t.G.L.L.V.N.N.N.N.N.N.",
"G+G+G+G+D+D+D+D+G+D+D+D+D+D+A+D+D+D+D+D+D+D+D+A+A+D+A+A+C+C+A+C+C+C+A+A+z+C+A+A+A+A+x+A+y+y+y+z+y+y+y+y+w+w+y+y+w+w+w+w+w+w+w+w+w+t+u+u+w+y+u+s+* S.S.*+*+*+S.S.S.S.S.S.S.S.S.S.S.- r+t+p+p+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+n+n+n+n+n+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+i+i+i+i+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+f+f+c+f+c+c+c+c+f+c+c+c+c+c+c+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+9+5+a+[+m.y 0.=+'+!+{+^+^+^+^+^+^+{+!+!++.5.h.h.4.%./ c H.Z.>+Z.c.<+1+3+3+3+3+3+3+3+3+3+4+1+<+[+Q S u.E.L.W.N.N.N.N.N.N.N.N.",
"G+G+G+G+D+D+D+D+D+D+D+D+D+D+D+D+D+A+D+D+D+D+D+D+D+D+A+A+C+C+A+A+C+z+A+A+A+z+A+A+A+A+A+x+y+y+z+z+y+w+y+y+y+w+w+w+z+w+w+w+w+w+w+w+w+u+y+w+w+w+u+k+& A.B.x.x.x.B.B.B.B.B.B.B.B.B.B.C.& k+t+p+p+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+p+n+p+n+n+n+p+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+i+i+i+i+i+i+f+f+f+f+f+f+f+f+f+f+i+f+f+f+f+f+f+f+f+f+f+c+c+c+c+f+c+c+c+c+c+f+c+c+c+c+9+9+9+9+9+9+9+9+9+9+9+9+9+c+c+5+7+a+J.y /.J.&+!+{+]+^+^+^+^+^+^+^+{+)+7.,.2.h.2.%.^ c @+++P.!+ +a.7+1+3+3+3+3+3+3+3+3+1+8+7+@+A :.r.E.N.N.N.N.N.N.N.N.V.N.N.",
"D+D+D+D+D+D+D+D+D+D+D+A+D+D+D+D+D+D+D+D+A+A+A+D+D+D+A+x+A+A+C+C+A+A+x+A+A+A+A+A+A+x+y+z+y+w+y+z+y+y+w+y+u+w+w+w+y+y+w+y+y+w+w+y+w+t+w+w+w+w+u+s+& o.p.p.p.p.p.p.p.p.p.p.p.p.p.p.b.& r+p+t+t+t+t+p+p+p+p+p+n+p+p+p+p+p+p+p+p+n+p+n+p+n+n+p+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+f+i+i+i+i+i+i+i+i+i+i+f+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+f+f+f+i+f+c+c+c+c+c+c+c+c+c+c+c+c+c+c+c+c+9+9+9+c+c+9+9+9+3+3+c+8+}+#+K S v.&+ +{+>+]+^+^+^+^+^+^+^+]+!+I.;.2.|.4.%./ c H.Z.>+{+&+a._+1+3+3+3+3+3+3+3+3+3+8+[+l.A c.G.E.L.N.N.N.N.N.N.N.N.N.N.N.",
"G+D+D+D+D+A+D+D+D+D+D+A+A+D+D+D+D+D+D+D+D+D+D+D+D+A+A+A+A+A+C+C+A+A+x+A+A+A+A+A+A+A+z+z+y+z+y+w+y+y+y+w+w+w+w+w+y+w+w+w+w+w+u+u+w+w+u+w+w+y+u+s+& b.8.8.8.8.8.8.8.8.8.8.8.8.8.8.b.& s+p+t+t+t+t+p+p+p+p+p+n+p+p+p+p+p+n+p+p+p+p+p+p+p+p+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+f+i+i+f+i+f+f+c+f+f+f+f+c+f+f+c+f+f+f+f+f+f+f+f+f+c+c+c+c+c+c+c+c+c+c+c+c+c+c+c+f+9+9+c+c+9+9+c+c+8+2+<+d.y l.@+&+{+~+~+~+^+]+^+^+^+^+^+{+{+!+O 5.2.k.%.^ c @+Z.%+%+Z.H.c.1+4+4+3+3+3+3+3+1+5+7+(+@.S r.D.L.N.N.N.N.V.N.N.N.N.N.N.N.N.",
"D+G+G+G+D+D+D+D+G+G+D+D+D+D+D+A+A+A+D+D+D+D+A+A+D+D+A+A+A+A+A+A+C+C+C+A+A+A+A+x+A+A+A+x+z+y+y+y+w+y+w+w+y+z+y+w+w+w+w+w+w+w+w+u+w+w+u+u+w+y+w+s+% !.~.~.~.~.~.~.~.~.~.~.~.~.~.!.!.& s+t+t+t+t+t+t+t+p+p+p+p+p+p+p+n+p+p+p+p+n+n+p+p+p+n+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+i+i+i+i+i+i+g+g+f+i+f+i+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+c+c+f+c+c+f+c+9+9+f+f+c+c+c+c+c+c+c+c+9+9+c+c+9+c+c+7+[+s.y ^.H.++Z.{+^+~+~+^+^+^+^+^+^+^+^+!+'+;.4.2.7.%./ c H.Z.>+%+%+Z.a.<+1+4+3+3+3+3+3+1+7+}+l.y c.I.E.T.L.N.N.N.N.V.N.N.N.N.N.N.N.V.",
"D+D+G+G+G+D+D+D+G+G+D+D+D+D+A+A+A+A+D+D+D+D+A+A+A+D+A+A+A+A+A+A+C+C+z+C+A+A+x+x+A+A+A+x+z+y+y+y+z+y+y+w+z+z+w+w+w+w+w+w+w+u+w+u+w+u+u+u+w+w+w+s+= Y !.!.J J J J J J J J !.Y !.J Y = k+t+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+n+p+p+p+n+n+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+i+i+i+i+i+i+g+g+f+f+f+i+f+i+f+f+f+i+f+f+f+f+f+f+f+f+f+f+c+f+f+c+f+f+c+f+c+c+9+9+f+f+c+c+c+c+0+0+c+c+9+9+c+c+8+7+a+@+y Q t.-+Z.~+%+~+~+~+^+^+^+^+^+^+^+{+!+!+G.;.4.4.E ^ c @+Z.%+%+>+!+++a.7+1+4+3+3+4+1+5+7+(+R Q t.G.L.L.N.N.N.N.N.N.N.N.N.N.N.N.N.V.N.",
"D+D+G+G+G+D+D+D+D+D+D+A+D+D+A+A+D+D+D+D+D+A+D+A+D+D+A+A+A+C+C+z+A+A+A+A+A+A+A+A+A+x+A+x+y+y+y+y+y+w+y+y+z+w+y+w+w+y+w+w+y+w+u+p+u+u+w+w+w+w+u+s+= r r D D D D D D D D D r D r r r = s+t+t+t+p+p+t+t+p+p+n+p+p+p+p+p+p+n+p+p+p+p+p+n+n+n+n+n+n+n+i+i+n+n+i+i+i+i+i+i+i+i+i+i+n+g+i+i+f+f+i+i+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+c+c+f+c+f+f+f+c+c+c+c+c+c+c+9+9+f+c+9+c+c+7+[+#+Q S r.&+ +Z.>+~+~+~+~+~+^+^+^+]+^+^+]+{+)+ +,.5.7.E ~ i H.Z.T.%+%+U.&+a._+1+4+4+3+3+1+7+[+l.A 0.I.E.L.L.N.N.N.N.N.N.N.V.N.V.N.N.N.N.N.V.",
"D+D+G+G+D+D+D+D+D+D+D+D+D+D+D+A+D+D+D+D+D+A+D+A+A+A+A+A+C+C+C+C+A+A+A+A+A+A+A+A+A+A+x+x+y+y+y+y+y+y+y+y+w+w+w+w+y+w+w+w+y+B+r+r+r+r+k+k+r+r+s+l+$ r r m m m s n n n f n n n n n s # s+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+p+n+p+p+p+n+p+n+n+n+n+n+i+i+n+n+i+i+i+i+i+i+i+i+f+i+n+g+i+i+f+f+i+i+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+f+c+c+c+f+f+c+c+c+c+c+c+c+c+9+9+c+c+8+7+7+}+:.y l.@+ +>+%+%+~+~+>+^+~+~+^+^+]+]+^+{+{+!+'+;.7.a.p ~ i M.Z.%+%+%+%+!+H.r.1+4+4+4+1+8+7+@+S B v.I.F.N.N.N.N.N.N.N.N.N.V.N.N.N.N.N.N.V.V.N.",
"G+G+G+G+D+D+D+D+D+D+D+D+D+D+D+A+D+D+A+A+A+A+D+A+A+A+C+C+A+A+C+C+C+C+z+C+A+A+x+A+A+z+A+A+w+y+y+y+y+y+y+y+y+w+x+y+w+w+w+w+y+q+l+- - - - - * * * % $ + + + + .   1 2 < < < < < < < 2 $ s+t+p+n+t+t+p+p+t+t+p+p+p+p+p+p+n+p+p+p+p+p+p+n+n+p+n+n+n+n+n+n+n+n+i+i+n+n+i+i+i+i+f+i+i+i+i+i+i+i+i+i+f+f+g+g+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+d+c+f+f+c+c+f+c+c+c+f+c+c+c+c+c+9+9+c+5+k+[+3.y c.I. +Z.{+%+%+~+~+~+~+~+~+~+^+^+^+{+^+{+!+!++.%.>.0 ) A I.Z.T.%+%+%+>+!+a.<+1+4+4+1+<+[+/.A c.G.E.P.L.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.V.V.V.",
"G+G+G+G+D+D+D+D+D+D+D+A+D+D+D+D+D+D+D+A+D+D+D+A+A+A+C+z+A+A+C+C+C+C+C+z+A+A+x+A+A+z+A+x+y+y+y+y+w+y+w+w+w+w+x+x+w+w+w+w+y+r+- # *+*+*+*+*+*+S.*+A.C.C.C.C.C..   2 9 4 9 9 9 9 9 2 $ s+t+p+p+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+p+p+n+n+n+n+n+n+n+n+n+n+n+n+i+i+n+n+i+i+i+i+i+i+f+i+i+i+i+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+c+d+c+f+i+c+c+c+c+c+c+c+c+c+c+c+c+8+8+7+<+t.y /.J.&+Z.%+%+%+%+~+~+~+~+~+~+~+^+^+]+^+{+{+{+)+a.-.>.i ~ R H.U.W.%+%+%+>+!+G.H.7+5+5+8+<+t.B :.v.D.L.N.N.N.N.N.N.V.N.N.N.N.N.N.N.V.N.N.V.V.L.T.U.",
"G+G+G+D+D+D+G+A+D+D+D+D+A+D+A+A+B+B+D+D+D+D+D+A+A+D+C+C+A+A+C+z+A+A+A+A+A+A+A+A+A+x+z+y+y+w+y+y+y+y+y+w+z+y+w+w+w+w+w+w+z+k+* S.S.S.S.S.S.S.S.S.p.A.A.A.A.o.o.. f d d d 9 b d d f $ s+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+p+p+n+p+p+n+n+n+n+n+n+n+n+n+n+n+i+i+i+i+i+i+n+g+i+i+i+i+i+i+i+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+f+c+c+c+c+f+c+c+c+f+c+c+c+c+5+a+[+s.y ..u.++Z.U.%+%+%+%+%+~+~+~+~+~+~+^+^+]+^+^+{+{+!+I.>.:.[ ~ >.G.U.W.%+%+%+%+!+&+a.5+5+7+}+#+Q ..u.G.F.L.L.N.N.N.N.N.N.V.V.N.N.N.N.N.N.N.N.N.N.V.T.G.-.",
"G+G+G+D+D+D+D+D+D+D+D+D+D+D+D+D+B+B+A+D+D+A+A+A+A+A+C+C+A+x+C+C+A+A+A+A+A+A+A+x+A+x+y+y+y+y+y+y+y+y+y+y+z+y+w+w+w+w+w+y+w+k+& A.B.B.B.B.B.B.B.B.p.o.o.o.o.o.b.. n d d d d d d n n $ s+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+p+n+p+p+n+p+n+n+n+n+n+n+n+n+n+n+i+i+i+i+i+i+g+g+f+f+i+i+i+i+i+i+i+i+f+f+f+f+f+f+f+i+f+f+f+f+f+f+f+f+f+f+f+c+c+f+c+c+c+c+c+c+c+c+c+c+5+5+7+a+J.S Q t.=+Z.T.%+%+%+%+%+%+~+~+~+~+~+~+^+^+]+^+^+^+{+)+&+>.:.{ ) 0.I.U..+%+%+%+%+>+)+r.@+<+2+(+^.y d.H.E.L.N.V.N.N.N.N.N.N.N.N.V.N.N.N.N.N.N.V.N.N.N.W.Z.a.q ",
"G+G+G+G+D+D+D+D+D+D+D+D+D+B+D+D+A+A+D+D+D+A+D+D+D+A+A+x+C+z+A+A+C+C+A+A+A+A+A+A+z+y+z+y+y+y+y+y+y+w+w+y+w+y+w+w+w+w+u+w+w+s+& o.o.p.p.p.p.p.p.o.~.b.b.b.b.b.!.. m n n n n n n n s # s+p+t+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+n+p+n+p+p+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+f+i+i+i+i+i+i+i+i+f+i+i+f+f+i+f+f+f+i+f+f+f+f+f+f+f+f+f+f+f+f+f+c+9+f+f+f+f+c+c+c+c+c+8+a+e+R.K R r.I. +U.T.%+%+%+%+%+%+%+~+~+~+>+^+^+^+]+^+^+^+^+!+=+R F ' ~ u. +U.W.%+%+%+%+>+!+&+0.|+/+/.A c.I.E.F.L.N.N.N.N.N.N.N.N.V.N.V.N.N.N.N.N..+N.N.V.V.L.U.G.v ^.",
"G+G+G+G+D+D+D+D+D+A+D+A+D+D+D+D+A+A+A+A+A+D+D+D+A+D+A+A+z+C+A+A+C+C+A+A+A+A+A+A+z+y+y+y+y+w+y+w+y+y+z+w+y+w+w+y+w+y+w+y+w+s+% b.b.8.8.8.8.8.8.b.H !.!.!.!.Y Y . D D s s s s s D J % s+p+t+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+p+p+n+n+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+f+f+i+f+f+f+f+f+f+c+f+f+f+f+c+f+f+c+f+f+f+9+c+c+f+f+c+c+g+8+7+a+J.S K d.H. +T.%+%+%+%+%+%+%+%+%+~+~+~+~+^+^+^+^+^+^+^+{+!+_+R F ' [ u.Z.L.%+W.%+%+%+>+)+-+0.`./.y :.v.I.T.N.N.N.N.N.N.N.N.N.N.N.N.V.N.N.N.N.N.V.V.N.N.N.W.P.E.%.v v.",
"G+G+G+D+D+D+D+D+D+D+A+D+B+B+A+A+D+D+D+A+D+A+D+A+A+A+A+A+C+C+C+C+C+C+A+A+A+A+A+A+z+z+y+y+y+u+w+w+y+y+w+y+y+w+w+w+w+w+w+w+w+s+% !.!.~.!.~.~.~.~.!.J J Y V V V Y   D D D D Y D D J @ - r+p+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+n+n+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+i+i+f+f+i+i+g+g+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+f+f+f+f+c+c+c+c+c+c+c+8+a+e+R.K S c.&+ +Z.T.%+%+%+%+%+~+%+%+%+~+%+~+]+~+^+^+^+^+^+^+^+!+=+:.e ; 0 I.E.T.%+W.%+%+%+>+ +;+m.F y ^.u.E.E.T.L.N.N.V.V.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.V.W.P.U.;.E -.H.",
"G+G+D+D+D+D+D+D+D+D+A+D+B+B+A+A+D+D+D+D+D+D+A+A+A+A+A+A+z+C+C+C+z+z+A+A+A+A+A+A+z+y+y+w+y+y+w+y+y+w+w+y+w+w+w+u+w+w+w+w+w+s+= Y Y Y Y Y J J J Y Y m s s s m m . $ = = = = = = & - l+m+p+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+n+p+n+n+n+n+n+n+n+i+i+n+n+i+i+i+i+i+i+i+i+i+i+f+f+i+i+g+g+i+i+f+f+f+f+f+f+f+f+f+f+f+c+f+f+f+c+f+f+f+f+f+f+f+c+j+8+7+a+$+S K l.M. +T.%+.+%+%+%+%+%+%+%+%+%+~+~+~+~+~+~+^+^+^+^+^+{+!+=+d.g ' x I.F.L.%+%+%+T.Z. +&+r.i g K t.H.T.N.N.N.N.N.N.N.V.N.N.N.N.N.N.N.N.N.N.N.N.N.V.N.N.V.V.W.U.5.O E 7.G.",
"G+G+G+D+D+D+D+D+D+D+D+D+B+B+D+D+D+A+A+D+D+A+D+D+A+A+D+A+A+A+A+A+C+z+A+A+A+A+A+x+z+y+z+y+w+y+y+y+y+y+y+y+y+y+w+w+y+w+w+w+w+s+= r D D D D D D D D s s s s s D D $ l+k+s+k+k+k+s+k+r+q+t+t+t+t+t+t+t+t+t+t+p+p+p+p+n+p+p+p+p+p+p+n+p+n+n+n+n+n+n+n+n+n+n+n+i+i+n+n+i+i+i+i+i+i+i+i+i+i+i+i+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+f+c+c+c+c+j+a+e+R.K R c.I. +Z.T.W.%+W.%+%+%+%+%+%+%+%+%+~+~+~+~+~+~+^+^+^+^+^+!+-+j.( ' c.G.F.W.W.%+%+T. +M.j.g : 7 >.I.E.T.L.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.V.N.N.N.V.N.W.T.n.E O O U.T.",
"G+G+D+D+D+D+D+D+D+D+D+D+B+B+D+D+D+D+D+A+D+D+A+D+A+A+A+A+A+A+A+A+C+C+A+A+A+A+A+x+z+z+y+y+y+y+y+w+w+y+w+x+r+r+s+s+s+s+s+s+s+l+$ r m m r m m n n n n n f n n n s # s+t+u+t+t+t+p+p+t+t+t+t+t+t+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+n+p+n+p+n+n+n+n+n+n+n+n+n+n+n+i+i+n+n+i+i+i+i+i+i+i+i+i+i+i+i+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+i+f+f+c+f+8+8+h+a+$+S y l.M.&+T.W.%+%+W.W.W.%+%+%+%+%+%+%+%+~+~+~+~+~+~+~+^+^+^+!+)+-+t.7 : j.D.L.W.W.U.Z. +&+a.0 / 7 F R G.T.L.N.N.N.N.N.N.N.N.N.N.V.N.V.N.N.N.N.N.N.N.N.N.V.V.N..+W.T.F.G N O +.P.W.",
"G+G+G+G+D+A+D+D+D+D+D+D+A+D+D+D+C+C+D+D+D+D+D+A+C+C+C+C+C+C+C+z+C+C+A+A+A+A+x+x+y+y+y+y+y+y+y+y+y+y+y+r+l+- - - - * * * * & $ + + + + .   1 2 < < < < < < < 2 $ s+u+t+t+t+t+t+t+t+t+p+p+t+t+p+p+t+t+p+p+n+p+p+p+p+p+p+p+p+p+p+p+p+n+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+i+i+i+f+f+i+i+i+i+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+c+f+f+c+f+5+a+e+R.K S c.I. +Z.T.%+%+.+.+W.%+%+%+%+%+%+%+%+%+~+~+~+~+~+^+~+~+^+^+^+)+(+j.g i H.E.L.W.W.U.H.J.Q 7 ^ 8 N ;.-.a.F.L.N.N.N.N.N.N.N.N.N.N.N.N.V.N.N.N.N.N.N.N.N.W.N.N.W.W.W.T.E.N X X O 7.T.W.",
"G+G+G+G+D+D+D+D+D+D+D+A+A+A+A+D+C+C+D+D+A+D+A+A+C+C+C+C+C+C+A+A+C+z+A+A+A+A+A+A+z+y+y+y+y+w+w+w+y+y+z+r+- # *+*+*+*+*+*+*+*+A.C.C.C.A.C..   2 9 9 9 9 9 4 9 2 $ s+u+t+t+w+t+t+t+t+t+p+p+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+n+n+p+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+i+i+i+i+f+f+i+i+i+i+i+i+f+f+f+f+f+f+f+f+f+f+c+f+f+f+c+f+j+h+h+a+Q.S y l.@+&+U.%+.+.+%+W..+.+W.%+%+%+%+%+%+%+~+%+~+~+~+~+^+^+~+^+{+!+_+;+:.7 S M.E.L.E.E.G.u.p ~ / c Z ;.2.2.,.E.L.N.N.N.N.N.N.N.V.N.N.N.N.N.N.N.N.N.N.N.N.N.V.W.V.N.W.W.T.F.N G ` ` N ++T.W.",
"D+D+D+D+D+D+D+D+D+D+A+D+A+A+D+A+D+D+D+D+D+A+A+A+C+C+A+A+C+z+A+A+A+A+A+A+A+A+y+y+y+y+y+y+x+y+y+w+w+w+z+k+* S.S.S.S.S.S.S.S.S.p.A.A.A.o.o.o.. f d d d b b d d f $ s+u+t+u+t+t+t+t+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+n+n+p+p+p+n+n+n+n+n+n+n+n+i+i+i+i+i+i+f+i+i+i+g+g+i+i+f+f+i+i+f+f+f+f+f+f+g+f+f+f+i+f+f+f+f+f+f+f+f+5+a+[+R.K S c.&+ +Z.U.%+%+%+%+.+.+.+.+W.%+%+%+%+%+%+%+~+%+~+%+~+~+^+^+^+{+!+=+#+F i c.G.E.E.I.$+@.[ ~ ] k *.2.|.2.4.,.F.L.L.N.W.W.N.N.N.N.N.N.N.N.N.N.N.N.V.N.N.N.N.N.V.V.N.V.V.T.D.N X ` ` X ,.Z.T.W.",
"D+D+D+D+D+D+D+D+D+D+D+D+A+A+D+D+D+A+D+A+D+D+D+A+C+C+A+A+C+C+A+x+A+A+A+A+A+A+z+y+z+y+y+y+x+y+y+y+w+w+z+s+& A.B.B.B.B.B.B.B.B.p.o.o.o.o.o.b.. n d d d d d d f n $ s+u+t+t+t+t+t+t+t+t+t+t+t+t+p+p+p+p+n+n+p+p+p+p+p+p+n+p+n+n+p+n+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+i+i+n+g+i+i+f+f+i+i+i+f+f+f+f+f+f+f+f+f+f+f+f+f+f+f+j+h+a+a+J.B Q d.M.I.>+%+%+%+%+%+W.%+.+.+V.W.%+%+%+%+%+%+%+%+~+~+~+~+~+~+^+{+!+'+-+t.u u j.M.I.G.u.v ^ ~ [ p N  .].<.9.|.,.;.T.N.N.N.W.L.N.N.V.N.N.V.N.N.V.N.N.N.N.N.N.N.N.N.V.V.N.W.T.F.N G W W `  .k.U.W.L.",
"D+D+D+D+D+D+D+D+D+A+A+A+D+A+A+A+D+D+D+A+D+A+A+A+A+A+C+C+C+C+x+x+z+C+A+A+x+A+y+y+y+y+y+u+y+w+y+w+y+w+y+s+& o.p.p.p.p.p.p.p.o.~.b.b.b.b.b.!.. s n n n n n n n s # s+u+t+t+t+t+t+t+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+p+n+p+p+n+n+n+n+n+n+n+n+n+p+n+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+f+f+f+f+f+f+f+f+f+f+f+f+c+j+k+[+s.K R r.&+ +Z.T.%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+~+~+%+~+%+~+~+~+]+]+>+!+&+Q.L u Q j.t.`.Q { ~ ] h G  .X {.].<.<.(.2.M D.L.V.N.N.N.N.N.V.N.N.V.N.V.N.N.N.N.N.N.N.N.V.N.V.N.N.W.T.D.O  .W T W  .M U.W.W.%+",
"D+D+D+D+D+D+D+D+D+D+D+A+A+A+A+A+D+D+A+A+A+A+A+A+A+A+C+C+C+C+x+x+C+z+A+A+A+A+A+z+y+y+y+y+y+y+w+w+y+w+w+s+% b.8.8.8.8.8.8.8.b.H !.!.!.!.!.!.. D s s s s s s D J % s+t+t+t+t+t+t+u+t+t+t+t+t+t+p+n+p+p+p+p+p+p+p+p+n+p+p+p+p+p+p+n+n+n+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+i+i+o+i+i+i+i+i+i+i+f+f+f+f+f+f+f+f+f+5+8+h+b+<+t.y Q j.M. +>+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+~+%+~+~+~+~+~+~+]+{+)+-+J.F #.#.m.0.0 ~ ) ~ p P X ].=.).).}.<.].2.*.5.E.L.N.N.N.N.N.V.N.V.V.V.N.N.N.N.N.N.N.N.N.N.N.V.N.W.L.T.E.O M ` T T ` G ;.T.W.W.%+",
"D+D+D+D+D+D+D+D+D+D+D+D+D+D+A+D+D+D+D+A+A+A+D+A+C+C+A+x+A+A+x+A+A+A+A+A+A+A+A+A+y+y+y+y+z+y+z+y+y+y+y+s+% !.~.~.~.~.~.~.~.!.J J Y Y V V Y   D D D D D D D J @ - r+u+t+t+t+t+p+p+t+t+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+p+n+n+n+n+n+n+n+n+n+n+n+n+n+n+i+i+n+n+g+g+g+g+i+i+i+i+i+i+f+f+g+g+f+f+f+f+f+f+f+h+e+|+s.y ^.u.&+ +Z.>+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+~+~+~+~+~+>+{+'+Q.3.C z.#.l ( ) ] 6 G X X ` W $.).).}.}.<.{.5.O F.L.N.N.N.N.N.N.N.V.N.N.V.N.N.N.N.N.N.N.N.N.L.W.N.W.L.U.q.M  .` T T =.` M G.U.%+%+W.",
"D+D+D+D+D+D+D+A+A+D+D+D+D+D+D+D+A+A+D+A+A+A+A+A+C+C+C+A+A+A+A+A+A+A+A+A+z+z+A+A+y+y+y+y+w+y+y+w+y+w+w+s+= Y Y Y Y Y J Y J Y Y m m m s s m . $ = = = = = = & - l+r+t+u+t+t+t+t+t+t+t+t+t+t+t+t+t+p+n+p+p+p+p+p+p+p+p+p+p+p+p+n+n+n+n+n+n+n+n+n+n+g+n+n+n+i+i+g+g+g+g+g+g+i+i+i+i+i+f+f+f+g+g+f+f+f+j+h+h+a+}+d.y /.J.-+ +>+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+~+~+~+~+^+!+)+-+Q.F [.z.w _ ' / p N X T U =.=.).).).).}.<.].2.;.q.T.N.N.N.N.N.N.V.N.N.V.N.N.V.N.N.N.N.N.N.N.N.W.W.W.W.T.k.N G ` T T =.].X N G.T.%+W.%+",
"D+D+D+D+D+D+D+D+D+A+A+A+D+A+A+A+D+D+D+A+A+A+A+A+C+C+A+A+A+A+A+A+A+A+A+A+z+z+A+x+y+y+y+w+y+w+y+w+w+w+y+s+= D D D D D D D D D s s s D s s D $ l+s+s+s+s+s+s+k+r+m+t+t+u+t+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+n+n+n+n+n+n+n+n+g+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+f+f+f+f+f+f+j+b+e+|+3.y 0.=+&+Z.U.P.%+%+%+%+%+%+%+%+%+%+%+%+%+%+W.%+%+%+%+%+%+%+%+%+~+~+~+~+^+!+-+`.[.l #.C g } k G X ` W T T =.=.=.=.).}.}.}.].|.4.5.E.L.N.N.N.N.N.V.V.V.N.N.N.V.N.N.N.N.V.N.N.N.W.V.W.T.U.q.M X W T =.=.].X  .k.U.W.W.W.W.",
"D+D+D+D+D+D+D+D+D+D+A+D+A+D+A+A+A+A+A+D+A+A+A+A+C+C+A+A+A+A+A+x+A+A+A+A+z+z+A+A+y+y+y+w+y+y+w+w+y+w+y+s+$ n n n n n n n n n n n n n f n m # s+u+u+u+t+u+u+t+u+t+u+t+t+t+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+n+p+n+n+n+n+n+n+n+n+n+n+n+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+i+f+f+f+g+j+h+a+a+$+:.y /.Q.&+Z.>+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+W.%+%+%+%+%+%+~+>+{+!+'+&+-+M.R g w w [.K q N ` T I I I U =.=.=.).).).}.}.9.(.4.M F.T.L.N.N.V.N.N.N.N.V.V.V.N.N.N.N.N.N.N.V.V.V.W.W.T.U.4.M  .W T =.=.=.W  .M U.T.W.%+%+%+",
"G+D+D+D+D+D+D+D+G+G+A+A+A+A+D+D+D+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+y+z+y+y+y+w+y+y+w+y+z+y+w+s+$ 2 < < < < < < < < < < < < < < 2 $ s+u+u+u+u+u+w+u+t+u+u+u+t+t+t+t+t+t+t+t+p+p+p+p+t+t+p+p+p+p+p+p+p+p+p+p+n+n+n+p+n+n+i+i+n+n+n+n+n+n+i+i+i+i+i+i+g+g+i+i+i+i+i+i+f+f+i+i+g+g+j+a+|+R.Q S c.&+ +)+{+>+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+>+!+-+$+K.L a a g S v.M.>.E  .` T I I I I U =.=.=.).).$.}.6.<.{.,.7.T.L.N.N.N.N.N.V.V.N.N.V.N.N.N.N.N.N.N.V.N.N.N.L.U.Z.,.G X W T ).=.).).{.,.+.U.%+%+W.%+W.",
"D+D+D+G+D+D+D+A+D+A+A+A+A+B+D+D+D+A+D+A+A+D+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+A+y+y+y+y+y+y+y+w+w+w+z+w+y+s+$ 2 9 9 9 9 9 9 9 9 9 9 9 9 4 9 2 $ s+u+u+u+u+t+w+u+u+u+t+t+t+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+p+p+n+p+p+p+p+p+p+n+n+n+i+i+n+p+n+n+n+n+i+i+i+i+i+i+g+g+i+i+f+f+i+i+f+i+j+h+b+a+a+J.y Q l.@+++{+%+~+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+>+Z.Z.++++++++u.A : _ a l w l.M.G.*.G X W =.I I U I U =.=.=.).).}.}.<.6.(.2.+.D.L.N.N.N.N.N.V.V.V.V.N.V.N.N.N.N.N.N.V.N.W.W.L.U.E.M G X W =.=.).=.).<.1.M q.T.%+%+%+%+%+",
"D+D+D+D+D+D+D+D+A+A+A+A+D+D+D+C+A+A+A+A+C+C+C+C+A+A+z+C+C+C+A+A+A+A+A+A+y+y+z+y+y+y+x+x+y+w+w+y+w+w+w+s+$ f d d d d d d b b d d b b d d f $ s+u+u+u+w+u+u+u+u+t+u+t+t+t+t+t+t+t+t+t+t+t+p+p+n+n+p+p+p+p+p+n+p+p+n+p+p+n+n+n+n+n+n+n+n+p+n+n+n+n+n+n+i+i+n+g+i+i+i+i+i+i+i+i+f+j+a+e+|+s.y ^.u.&+ +Z.{+%+%+~+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+>+ +-+O.K.Q 7 / / : u C F d.H.I.G.,.G ` T T I I U I I T =.=.=.).).}.}.6.(.4.,.F.T.L.N.N.N.N.N.N.N.N.N.N.N.N.W.N.N.W.W.N.N.N.L.E.n.G  .` W =.).=.).}.<.].|.O G.U.%+%+%+%+%+",
"D+D+D+D+D+D+D+A+D+D+D+A+D+D+C+C+A+A+D+A+C+C+C+C+A+C+C+C+C+C+A+A+A+A+x+A+y+y+y+y+y+y+x+x+w+y+y+w+w+w+w+s+$ n f d d d d d d d d d d d d f n $ s+u+u+u+u+u+u+u+t+u+t+t+t+t+t+t+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+p+p+n+n+n+n+n+n+n+n+n+n+n+n+p+n+n+i+i+g+g+i+i+i+i+i+j+j+h+b+a+(+d.o /.J.;+)+>+%+%+%+~+~+~+~+%+%+%+~+%+%+%+%+%+%+%+%+%+%+T.Z.Z.++++++++a.v ! ) : : u L F K Q Q. +U.U.*.G X T I U I I I U U =.=.=.=.).$.}.6.9.|.,.;.L.N.N.N.N.N.N.V.N.V.N.N.N.N.N.W.V.N.V.W.W.L.T.U.5.G  .` W =.).}.).).<.<.{.2.5. +>+%+%+%+%+%+",
"D+D+D+D+D+D+D+D+A+A+A+D+D+A+D+D+D+D+A+A+D+A+A+x+C+C+A+C+C+z+A+A+z+z+x+A+x+x+y+y+y+y+w+y+y+w+y+y+w+w+w+e+$ s n n n n n n n n n n n n n n s # s+u+u+u+u+u+t+w+w+t+t+t+p+p+t+t+p+p+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+p+n+p+n+n+n+n+n+n+n+n+i+i+i+i+i+i+n+n+g+g+i+i+g+h+k+e+R.K B 0.=+ +)+!+>+~+%+%+%+~+~+%+~+%+%+~+%+%+%+~+%+%+%+%+%+%+Z.I.M.`.m.o : ) ^ ] k N ;...Q F S r.I.Z.Z.Z.,.G ` W T I U U I U U T U =.).).}.}.}.<.(.g.M D.L.N.V.N.N.N.N.N.N.N.N.N.N.N.V.N.V.N.V.W.W.T.G.O  .X W W =.}.}.).}.<.<.(.4.N U.T.%+%+%+%+%+%+",
"B+B+D+D+D+D+D+D+A+A+A+A+D+D+D+D+D+D+A+A+A+A+A+x+C+C+A+z+C+C+A+A+z+z+A+A+x+x+z+w+y+w+y+y+w+z+y+y+w+y+w+s+% J D s s s s s D D s s s s s D J % k+u+u+t+u+u+u+u+u+t+u+u+p+p+t+t+p+p+t+t+t+t+t+t+p+n+p+p+p+p+p+p+p+p+p+p+p+p+p+n+n+n+n+n+n+n+n+n+i+i+i+i+i+i+n+n+g+j+h+b+a+}+J.Q Q l.@+=+!+~+%+~+~+~+~+%+~+~+~+%+%+%+%+%+%+%+>+Z.Z.++++++++++u.E ^ ~ ) ) [ t Z ;.,.,.,.%.A ^.H. +T.L.U.*.G X W U I I U I U I =.=.=.=.).).}.}.6.f.2.*.n.E.L.N.N.N.N.N.N.N.N.N.N.N.N.N.V.N.N.N.L.L.T.F.N M ` W =.=.).).}.}.<.<.<.1.;.;.U.%+%+%+%+%+%+%+",
"D+D+D+D+D+D+D+A+D+D+D+D+A+A+D+D+A+D+A+D+C+C+C+C+A+C+C+C+C+C+A+A+A+A+A+A+y+z+y+y+y+y+x+x+y+y+y+w+y+w+z+k+- @ J D D D D D D D D D D D D J @ - r+u+u+u+u+t+u+u+t+u+u+t+p+p+t+t+t+t+t+t+t+t+t+t+n+p+p+p+p+p+n+p+p+p+p+p+p+n+n+n+n+n+n+n+n+n+i+i+n+n+i+i+i+i+n+g+j+a+e+|+s.y ^.r.&+)+)+!+>+~+%+~+~+%+%+%+~+%+%+%+%+%+%+~+%+>+ +-+O.K.i.g 7 ) ! ] 6 h *. .X X  .,.-...q >.I. +Z.T.U.U.,.G ` T T I I I U U U =.=.=.=.).).).}.<.6.1.5.;.F.L.N.N.N.N.N.N.V.V.V.N.N.N.V.V.N.N.N.W.U.Z.5.G X ` ].=.).).}.<.}.9.9.<.6.1.O u.U.%+%+%+%+%+%+%+",
"D+D+D+D+D+D+A+A+D+D+D+D+A+A+D+D+D+D+A+A+C+C+C+C+A+A+y+z+z+C+A+A+A+A+A+A+y+y+y+y+y+y+x+x+y+w+y+y+w+w+z+q+l+- & = = = = # = = = = = = = & - l+r+u+u+u+t+u+u+u+t+t+u+t+p+p+t+t+t+t+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+n+p+p+p+n+n+n+n+n+n+i+i+n+n+i+n+g+j+b+a+a+(+:.y /.J.;+)+>+~+~+~+~+~+~+~+~+%+~+%+>+{+!+Z.++++++++++G.-.v ! ) ) { / i Z P *.1.<.<.{.X  .+.v R v.H.Z.W.W.T.U.*.G X T U I U I U I I U =.=.=.).).}.}.}.<.f.2.O G.L.N.N.N.N.N.N.V.V.N.V.V.N.N..+V.N.L.L.U.E.,.M  .W ).=.=.}.}.<.9.9.<.6.6.f.g.;.++U.%+%+%+%+%+%+%+",
"D+D+D+D+D+D+D+A+D+D+D+D+D+D+A+A+D+D+D+D+C+C+C+C+C+C+A+A+C+C+A+A+A+A+A+A+z+y+y+y+y+y+y+y+z+y+y+y+w+w+y+B+r+r+s+s+s+s+s+s+s+s+s+s+s+s+s+k+r+r+x+u+u+u+t+u+u+t+t+t+u+t+t+t+t+t+t+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+n+p+n+p+p+n+p+n+n+n+n+n+n+n+n+n+n+i+g+h+k+|+R.K B c.=+&+)+!+>+^+~+~+~+~+%+~+~+%+%+%+>+!+&+-+$+K.i.F : ) ) ^ ] 6 M  . . .X X ` (.<.<.{.N -.q q a. +Z.U.W.L.Z.E.M  .` T T I U I I I I U U =.=.).=.$.}.}.6.f.2.4.5.F.L.N.N.N.N.N.N.N.N.N.N.N.N.N.V.V.V.L.Z.q.M  .` W <.).).<.<.<.9.}.6.6.9.f.g.4.n.U.%+%+%+%+%+%+%+%+",
"D+D+D+D+D+A+D+A+D+A+D+D+D+D+A+D+A+D+D+A+C+C+C+C+C+C+A+A+C+C+x+A+A+A+A+A+C+y+w+y+y+y+y+z+w+w+y+y+w+w+w+w+w+w+w+w+w+u+w+w+u+w+u+u+w+w+u+u+u+w+u+u+w+u+u+u+w+t+w+u+t+t+t+t+t+t+t+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+p+p+n+p+p+n+n+n+n+n+n+n+n+n+j+b+a+a+(+t.y K l.@+&+!+>+~+~+^+~+^+>+!+!+Z.'+++++++++++u.E 0 ~ ) , { { c p Z N  .(.$.$.$.$.$.$.].1. .M E q ^.v. +T.W.W.W.T.E.M  .` W U U U I U U I I U U =.=.).$.$.}.<.<.f.4.M F.L.W.N.N.N.N.N.N.N.N.N.N.N.V.V.W.L.T.U.,.M  .` ].).).).<.<.<.6.6.6.6.6.6.h.5.+.U.>+%+%+%+%+%+%+%+%+",
"D+D+D+D+D+D+D+D+D+D+A+D+D+D+D+D+A+D+D+A+A+A+A+A+C+C+C+z+A+x+z+y+A+A+x+A+C+z+y+y+y+y+y+w+w+z+w+w+y+w+w+w+w+w+w+w+w+w+p+p+y+w+t+w+u+u+u+u+u+u+u+u+u+u+u+t+t+u+u+t+u+t+t+t+t+t+t+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+p+n+p+n+n+n+n+n+n+n+n+n+n+j+k+e+/+3.y ^.H.&+)+!+!+^+~+~+~+^+^+!+&+=+M.`.K.i.F g { ) ! ] ] 6 G  . . .X X {.(.<.=.).).$.$.).W *.%.q A -.I. +Z.T.%+.+W.U.E.G  .` W T T I U I I I U U U =.).).).}.}.<.9.6.1.+.q.F.L.N.N.N.V.N.N.N.N.N.N.N.N.V.W.W.U.G.N  .` (.].=.}.}.<.<.<.6.6.e.e.e.e.e.h.7.a.U.W.%+%+%+%+%+%+%+%+",
"D+D+D+D+D+D+A+D+D+D+D+D+D+A+D+D+A+A+A+A+A+A+A+A+C+z+y+z+A+A+z+z+A+A+A+A+y+y+y+y+y+y+y+w+y+w+y+w+w+y+w+w+w+w+w+w+w+p+p+p+w+w+u+u+w+u+u+u+w+u+u+u+u+w+u+u+u+u+t+t+t+t+t+t+t+t+t+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+n+p+n+n+n+n+p+n+j+j+m+b+q+}+J.Q K m.`.;+&+!+!+'+'+'+&+&+&+'+'+H.-.p 0 ~ ) ) { { c t &.%.,.2.(.$.$.$.$.$._.$.).}.).=.<.` X *.%.v S t.&+Z.%+N..+W.W.T.E.G  .` T U $.$.I I I I U I U ).=.=.).}.}.}.6.<.{.g.+.D.L.V.V.N.N.N.V.V.N.N.N.N.N.L.L.T.U.5.N *.` ].).}.}.}.<.<.<.6.6.6.e.6.e.f.f.g.;.I.U.W.%+%+%+%+%+%+%+%+",
"D+D+D+D+D+D+D+D+D+D+D+D+D+A+A+D+A+A+A+A+C+C+A+A+C+z+A+A+C+C+A+x+A+x+A+x+y+y+y+y+y+y+w+y+y+z+w+w+y+y+w+w+w+w+u+w+w+u+u+u+w+w+u+u+u+u+u+u+u+u+u+t+u+u+u+t+u+t+t+t+t+t+t+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+p+p+n+p+n+o+o+o+n+n+n+t+j+a+e+|+s.y ^.M.&+&+&+&+-+;+$+`.K.i.L g : { ) ! ^ ] 8 k G 2.2.2.2.|.|.1.(.<.<.$._._._._._.$.}.).).<. .O q A >.u. +Z.T.%+W.W.V.W.Z.n.G  .` T T U U I I U I I U =.=.=.=.).).}.}.6.<.f.4.N F.L.L.V.N.V.N.N.V.V.V.V.N.N.V.L.Z.q.M  .X {.=.).).<.6.9.<.6.6.6.e.e.e.e.e.f.g.k.+. +T.%+%+%+%+%+%+%+%+%+",
"D+D+A+D+D+D+D+A+D+D+D+A+D+A+D+A+A+D+A+A+C+C+A+A+C+z+A+A+C+C+A+A+A+x+x+A+y+y+y+w+w+z+y+y+y+z+y+w+y+z+w+w+w+w+w+w+w+u+w+u+w+y+u+t+u+u+w+u+u+u+u+u+t+u+u+u+u+t+t+t+t+t+t+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+p+p+n+p+p+p+t+t+h+m+q+k+e+Y.'.w [.w.#+@+&+'+H.a.v q } ~ ) , , : 7 c t &.Z ;.4.1.<.}._._._._._.<.$.$.).$._._._._.$.$.].{.X *.O v R t.=+ +W..+%+%+%+%+W.U.n.G X ` T U U U U I I I I U U =.=.=.).).}.}.}.<.6.1.7.7.L.N.N.N.N.N.N.V.V.V.N.N.L.L.T.U.,.M *.X ].).).}.<.<.<.<.6.6.9.e.e.f.e.e.e.h.k.;.E.U.%+%+%+%+%+%+%+%+%+%+",
"D+D+D+D+D+D+D+D+A+A+D+D+A+D+D+A+A+A+A+A+C+C+C+C+A+A+A+A+z+C+A+A+A+A+x+A+y+y+y+y+w+y+w+w+y+y+w+w+w+w+w+w+w+u+u+u+w+w+u+u+w+w+p+p+w+u+u+u+u+u+u+u+t+t+u+u+u+t+t+t+t+t+t+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+p+n+n+p+p+p+t+j+h+e+l+/+x.z z p.x.#.w e _ { ) ! ! ^ ] 8 k G 4.4.4.2.2.|.|.|.(.(.<.<._.}.}._._._._._._.).)._._.).).=.W  .%.v A v u. +Z.U.W.W..+.+.+.+W.Z.5. .` W T =.$.U U U I I I I U U =.=.=.).}.}.}.}.<.h.g.+.D.L.N.N.N.N.N.N.V.N.N.N.W.T.Z.q.M  .X {.].].}.}.<.6.6.6.9.9.6.e.6.f.6.e.f.f.h.7.;.U.%+%+%+%+%+%+%+%+%+%+%+",
"D+D+D+D+D+D+D+D+A+A+D+D+A+D+D+A+D+A+A+A+C+C+C+C+A+A+A+A+C+C+A+A+A+A+A+x+y+y+y+z+y+w+y+w+y+w+w+y+y+w+w+w+w+w+w+u+w+w+w+u+w+w+p+p+u+u+u+u+u+u+u+w+u+u+t+u+u+t+w+t+t+t+t+t+t+t+p+p+t+t+p+p+p+p+p+p+p+p+p+t+m+r+k+e+e+e+[+|+w.C l l | > ; ' ' { : 7 c t &.&.%.+.4.2.(.6.6.6.6._._._._._._._._._.}.}._._._._._.$.$.$._._.$.].X M E q S t.H. +>+%+.+.+.+.+.+%+W.U.,.M X W T U $.$.I I U U U I I U U =.=.).}.$.}.<.9.{.g.,.n.U.L.N.N.V.N.N.V.V.N.N.W.T.E.+.M *.` <.).}.}.<.6.<.6.6.9.6.e.e.e.e.e.e.f.f.f.g.%.I.U.%+%+%+%+%+%+%+%+%+%+%+",
"D+D+D+D+D+D+D+D+B+B+D+D+D+D+A+D+A+A+A+A+C+C+x+x+C+C+A+A+A+A+A+A+z+y+A+x+y+y+z+z+y+y+y+y+z+z+w+w+w+w+w+w+w+w+u+w+w+w+u+u+w+w+p+p+u+u+w+u+u+u+u+t+u+u+t+u+t+u+t+t+t+t+t+t+t+t+p+p+p+p+p+p+p+p+p+p+p+p+p+q+s.[.#.#.H j j j j | 5 _ c q ;.4.4.4.4.4.2.2.|.|.1.1.(.f.6.6.6.6._.}.}._._._._.}._._._._._.<.$._._._.$._._._.}.X v y Q t.&+ +Z.>+%+%+%+%+%+%+W.T. ++.G X W T =.$.U U U U U I U U U =.=.=.=.).}.}.<.6.<.f.5.+.U.L.W.N.N.V.N.N.N.N.N.W.T.n.E O  .(.<.<.}.}.}.<.<.6.6.9.9.6.e.f.e.f.f.f.e.f.f.g.%.&+U.%+%+%+%+%+%+%+%+%+%+%+"]
save_sim_xpm=[
"16 16 33 1",
" 	c None",
".	c #2D2E99",
"+	c #3A399A",
"@	c #333AA7",
"#	c #4645A1",
"$	c #4B4EA4",
"%	c #4E52B2",
"&	c #5D52AB",
"*	c #5A5AAB",
"=	c #565AB7",
"-	c #5A5AC4",
";	c #6663D0",
">	c #717BBF",
",	c #8383A5",
"'	c #898AB7",
")	c #8B8CA5",
"!	c #9698D1",
"~	c #A1A1B4",
"{	c #A8A7D7",
"]	c #A9AED5",
"^	c #B9B8CD",
"/	c #BCBCE0",
"(	c #C6C5EA",
"_	c #C3CFD0",
":	c #CBCEC9",
"<	c #D4D6D3",
"[	c #D4D4EB",
"}	c #DCDCE7",
"|	c #DDDFDC",
"1	c #F0F1FB",
"2	c #F2F4F1",
"3	c #F9FFFF",
"4	c #FEFFFC",
"  %^<:::::::<]# ",
" >%}111111111/-&",
" >%[2<<<<<<<2/-&",
" >%[2}}}}}}}2/-&",
" >%[2}|||||}2/-&",
" >%[2<<<<<<<2/-&",
" >%[111111112/-&",
" >%[222222222/-&",
" >%=>{]]]{{]]!;%",
" >;;;;;;;--;;;;&",
" >;;='!',~({@@-*",
" >;;='$.~<4(..=*",
" >;;='++^24(..=*",
" >;;=,#>}14/..=*",
" >;;=)~[132^..-*",
"  *%#):__::~##$ "]
bsmedit_xpm=[
"32 32 15 1",
" 	c None",
".	c #9C3C09",
"+	c #A84D1D",
"@	c #FBC0A0",
"#	c #F9B28C",
"$	c #F7A478",
"%	c #F59663",
"&	c #F59763",
"*	c #F3884F",
"=	c #F58244",
"-	c #F17939",
";	c #EA590D",
">	c #ED631B",
",	c #EF6D28",
"'	c #F37736",
"                                ",
"                                ",
"                                ",
"                                ",
"                 ...........    ",
"                .+@@@@@@@@@+.   ",
"                .###########.   ",
"                .$$$$$$$$$$$.   ",
"                .%&&%&&%&&&%.   ",
"                .***********.   ",
"           ...........==----.   ",
"          .+@@@@@@@@@+.;;;;;.   ",
"          .###########.>>>>>.   ",
"          .$$$$$$$$$$$.,,,,,.   ",
"          .%&&%&&&&&&&.'----.   ",
"          .***********.====..   ",
"     ...........==-=-=......    ",
"    .+@@@@@@@@@+.;;;;;.         ",
"    .###########.>>>>>.         ",
"    .$$$$$$$$$$$.,,,,,.         ",
"    .%&&%&&%&&&%.-'-''.         ",
"    .***********.====..         ",
"    .-----=--=-=......          ",
"    .;;;;;;;;;;;.               ",
"    .>>>>>>>>>>>.               ",
"    .,,,,,,,,,,,.               ",
"    .-----'-'-''.               ",
"    ..=========..               ",
"     ...........                ",
"                                ",
"                                ",
"                                "]
